print("   **     **  ")
print(" ****** ****** ")
print("  *********** ")
print("   ********  ")
print("    ******   ")
print("    AAAAAA    ")
print("     ****     ")
print("      **      ")
print("sasha popa")
print("polya popa")